services:
  crate-3:
    image: crate:3.3.5
    container_name: crate-3
    ports:
      - "4280:4200"
      - "5480:5432"
    environment:
      CRATE_HEAP_SIZE: 1g
    command: ['-Cdiscovery.type=single-node']

  crate-4:
    image: crate:4.8.4
    container_name: crate-4
    ports:
      - "4281:4200"
      - "5481:5432"
    environment:
      CRATE_HEAP_SIZE: 1g
    command: ['-Cdiscovery.type=single-node']

  crate-5:
    image: crate:5.10.16
    container_name: crate-5
    ports:
      - "4282:4200"
      - "5482:5432"
    environment:
      CRATE_HEAP_SIZE: 1g
    command: ['-Cdiscovery.type=single-node']

  crate-6:
    image: crate:6.2.4
    container_name: crate-6
    ports:
      - "4283:4200"
      - "5483:5432"
    environment:
      CRATE_HEAP_SIZE: 1g
    command: ['-Cdiscovery.type=single-node']
