using NSCI.Configuration;
using NSCI.Testing;
using System.Data.Common;

namespace NSCI.Tests.TableDefinition;

// https://www.postgresql.org/docs/current/ddl-identity-columns.html
[SqlTest(SqlFeatureCategory.DDL, "Test IDENTITY columns with GENERATED ALWAYS and GENERATED BY DEFAULT", DatabaseType.PostgreSql)]
public class PostgresIdentityColumnTest : SqlTest
{
    protected override void SetupPg(DbConnection connection)
    {
        using DbCommand cmd = connection.CreateCommand();

        cmd.CommandText = @"CREATE TABLE identity_test (
            id   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            code INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 10),
            name TEXT NOT NULL
        )";
        cmd.ExecuteNonQuery();

        cmd.CommandText = "INSERT INTO identity_test (name) VALUES ('Alice')";
        cmd.ExecuteNonQuery();
        cmd.CommandText = "INSERT INTO identity_test (name) VALUES ('Bob')";
        cmd.ExecuteNonQuery();
    }

    protected override void ExecutePg(DbConnection connection, DbConnection connectionSecond)
    {
        using DbCommand cmd = connection.CreateCommand();

        cmd.CommandText = "SELECT id FROM identity_test ORDER BY id";
        var ids = new List<int>();
        using (DbDataReader reader = cmd.ExecuteReader())
        {
            while (reader.Read())
                ids.Add(reader.GetInt32(0));
        }
        AssertEqual(2, ids.Count, "Should have 2 rows");
        AssertEqual(1, ids[0], "First id should be 1 (GENERATED ALWAYS)");
        AssertEqual(2, ids[1], "Second id should be 2");

        cmd.CommandText = "SELECT code FROM identity_test ORDER BY code";
        var codes = new List<int>();
        using (DbDataReader reader = cmd.ExecuteReader())
        {
            while (reader.Read())
                codes.Add(reader.GetInt32(0));
        }
        AssertEqual(100, codes[0], "First code should be 100 (START WITH 100)");
        AssertEqual(110, codes[1], "Second code should be 110 (INCREMENT BY 10)");

        AssertThrows<Exception>(
            () =>
            {
                using DbCommand badCmd = connection.CreateCommand();
                badCmd.CommandText = "INSERT INTO identity_test (id, name) VALUES (999, 'Eve')";
                badCmd.ExecuteNonQuery();
            },
            "Explicit value for GENERATED ALWAYS AS IDENTITY column should be rejected");
    }

    protected override void CleanupPg(DbConnection connection)
    {
        using DbCommand cmd = connection.CreateCommand();
        cmd.CommandText = "DROP TABLE IF EXISTS identity_test CASCADE";
        ExecuteIgnoringException(() => cmd.ExecuteNonQuery());
    }
}
