using NSCI.Configuration;
using NSCI.Testing;
using System.Data.Common;

namespace NSCI.Tests.TableDefinition;

// https://www.postgresql.org/docs/current/ddl-identity-columns.html
[SqlTest(SqlFeatureCategory.DDL, "Test IDENTITY columns with GENERATED ALWAYS and GENERATED BY DEFAULT", DatabaseType.PostgreSql)]
public class PostgresIdentityColumnTest : SqlTest
{
    protected override void SetupPg(DbConnection connection)
    {
        using DbCommand cmd = connection.CreateCommand();

        cmd.CommandText = @"CREATE TABLE identity_test (
            id   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            code INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 10),
            name TEXT NOT NULL
        )";
        cmd.ExecuteNonQuery();

        string[] names = ["'Alice'", "'Bob'", "'Carol'"];
        foreach (string name in names)
        {
            cmd.CommandText = $"INSERT INTO identity_test (name) VALUES ({name})";
            cmd.ExecuteNonQuery();
        }
    }

    protected override void ExecutePg(DbConnection connection, DbConnection connectionSecond)
    {
        using DbCommand cmd = connection.CreateCommand();

        // ALWAYS identity: ids must be sequential starting at 1
        cmd.CommandText = "SELECT id FROM identity_test ORDER BY id";
        var ids = new List<int>();
        using (DbDataReader reader = cmd.ExecuteReader())
        {
            while (reader.Read())
                ids.Add(reader.GetInt32(0));
        }
        AssertEqual(3, ids.Count, "Should have 3 rows");
        AssertEqual(1, ids[0], "First id should be 1");
        AssertEqual(2, ids[1], "Second id should be 2");
        AssertEqual(3, ids[2], "Third id should be 3");

        // BY DEFAULT identity: codes start at 100 and increment by 10
        cmd.CommandText = "SELECT code FROM identity_test ORDER BY code";
        var codes = new List<int>();
        using (DbDataReader reader = cmd.ExecuteReader())
        {
            while (reader.Read())
                codes.Add(reader.GetInt32(0));
        }
        AssertEqual(3, codes.Count, "Should have 3 code values");
        AssertEqual(100, codes[0], "First code should be 100");
        AssertEqual(110, codes[1], "Second code should be 110");
        AssertEqual(120, codes[2], "Third code should be 120");

        // BY DEFAULT: explicit override is allowed
        cmd.CommandText = "INSERT INTO identity_test (code, name) VALUES (999, 'Dave')";
        cmd.ExecuteNonQuery();

        cmd.CommandText = "SELECT code FROM identity_test WHERE name = 'Dave'";
        long overrideCode = Convert.ToInt64(cmd.ExecuteScalar()!);
        AssertEqual(999L, overrideCode, "Explicit code override should be accepted for BY DEFAULT identity");

        // ALWAYS: explicit insert must be rejected
        AssertThrows<Exception>(
            () =>
            {
                using DbCommand badCmd = connection.CreateCommand();
                badCmd.CommandText = "INSERT INTO identity_test (id, name) VALUES (999, 'Eve')";
                badCmd.ExecuteNonQuery();
            },
            "Explicit value for GENERATED ALWAYS AS IDENTITY column should be rejected");

        // Verify attidentity in pg_attribute: 'a' = ALWAYS, 'd' = BY DEFAULT
        cmd.CommandText = @"SELECT attname, attidentity
                            FROM pg_attribute
                            WHERE attrelid = 'identity_test'::regclass
                              AND attname IN ('id', 'code')
                            ORDER BY attname";

        var identityMap = new Dictionary<string, char>();
        using (DbDataReader reader = cmd.ExecuteReader())
        {
            while (reader.Read())
                identityMap[reader.GetString(0)] = reader.GetChar(1);
        }

        AssertEqual('a', identityMap["id"], "id should have attidentity 'a' (ALWAYS)");
        AssertEqual('d', identityMap["code"], "code should have attidentity 'd' (BY DEFAULT)");
    }

    protected override void CleanupPg(DbConnection connection)
    {
        using DbCommand cmd = connection.CreateCommand();
        cmd.CommandText = "DROP TABLE IF EXISTS identity_test CASCADE";
        ExecuteIgnoringException(() => cmd.ExecuteNonQuery());
    }
}
