services:
  singlestoredb-0.1.7:
    image: ghcr.io/singlestore-labs/singlestoredb-dev:0.1.7
    container_name: singlestoredb-dev-0.1.7
    ports:
      - "3366:3306"
      - "8006:8080"
      - "9006:9000"
    environment:
      ROOT_PASSWORD: "password"
    healthcheck:
      test: ["CMD", "mysql", "-h127.0.0.1", "-P3306", "-uroot", "-ppassword", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  singlestoredb-0.2.79:
    image: ghcr.io/singlestore-labs/singlestoredb-dev:0.2.79
    container_name: singlestoredb-dev-0.2.79
    ports:
      - "3367:3306"
      - "8007:8080"
      - "9007:9000"
    environment:
      ROOT_PASSWORD: "password"
    healthcheck:
      test: ["CMD", "mysql", "-h127.0.0.1", "-P3306", "-uroot", "-ppassword", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
